apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: mongo
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  azureFile:
    shareName: mongodata
    readOnly: false
  claimRef:
    namespace: default
    name: mongodata