apiVersion: batch/v1
kind: Job
metadata:
  name: nodebb-init
  labels:
    app: nodebb-init
spec:
  activeDeadlineSeconds: 1000
  template:
    metadata:
      name: nodebb-init
    spec:
      containers:
      - name: nodebb-init
        image: nodebb:v1
        env:
        - name: NODE_ENV
          value: 
        - name: BLUEFYRE_AGENT_ID
          valueFrom:
            secretKeyRef:
              name: bluefyre-agent-id
              key: agentid         
        - name: mongo__host
          value: mongo
        - name: mongo__port
          value: "27017"
        - name: mongo__database
          value: nodebb
        - name: mongo__uri
          value: 
        - name: setup
          value: "true"
        command: ["node", "app"]          
      restartPolicy: OnFailure
